#!/bin/bash
# set -euox pipefail
set -euo pipefail


SD="$(dirname "${BASH_SOURCE[0]}")"

# print help
if [ -z "$1" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    echo "Usage: cat <pkgslist> | backport \
[--checkonly] [--binonly] [--removeonly] [--onlyunsat] [--nosrcfix] [--oneshot] \
[--metadata <folder>] \
<basename> <newerprefix> <olderprefix>"
    echo ""
    echo "The script backport expects to find the following metadata files in the current directory:"
    echo "newerprefix_Packages, newerprefix_Sources, olderprefix_Packages, olderprefix_Sources"
    echo "If --metadata <folder> is given, these files are automatically generated by concatenating"
    echo "all binary-amd64/Packages and source/Sources files under folder/dists/<prefix>/."
    echo ""
    echo "Example: echo gnome-core | backport gnome-core testing stable"
    echo "Example: cat debootstrap.list | backport minimal sid empty"
    exit 0
fi

OPT_CHECKONLY=false
OPT_BINONLY=false
OPT_REMOVEONLY=false
OPT_ONLYUNSAT=false
OPT_NOSRCFIX=false
OPT_ONESHOT=false
METADATA=""
EXTRA_PARAMS=()
# Process options
while [[ $# -gt 0 ]]; do
    case "$1" in
        --checkonly)
            OPT_CHECKONLY=true
            shift
            ;;
        --binonly)
            OPT_BINONLY=true
            shift
            ;;
        --removeonly)
            OPT_REMOVEONLY=true
            shift
            ;;
        --onlyunsat)
            OPT_ONLYUNSAT=true
            shift
            ;;
        --nosrcfix)
            OPT_NOSRCFIX=true
            shift
            ;;
        --oneshot)
            OPT_ONESHOT=true
            shift
            ;;
        --metadata)
            if [ -z "$2" ] || [ "${2:0:1}" = "-" ]; then
                echo "Error: --metadata requires a folder argument" >&2
                exit 1
            fi
            METADATA="$2"
            shift 2
            ;;
        *)
            # Break out of the loop when we hit the first non-option argument
            break
            ;;
    esac
done

# warning if not installed
if ! command -v dose-distcheck &> /dev/null; then
    echo "Warning: dose-distcheck package is not installed. Exiting."
    exit 1
fi

if ! command -v dose-builddebcheck &> /dev/null; then
    echo "Warning: dose-builddebcheck package is not installed. Exiting."
    exit 1
fi

generate_metadata_for_suite() {
    local suite="$1"
    local suite_dir="$METADATA/dists/$suite"

    if [ ! -d "$suite_dir" ]; then
        echo "Error: Suite directory '$suite_dir' not found in metadata folder"
        return 1
    fi

    # Packages (binary-amd64)
    local packages_file="${suite}_Packages"
    find "$suite_dir" -path "*/binary-amd64/Packages" -type f -exec cat {} \; > "$packages_file"
    if [ ! -s "$packages_file" ]; then
        echo "Warning: No Packages files found for suite '$suite' under $suite_dir"
        touch "$packages_file"
    fi

    # Sources
    local sources_file="${suite}_Sources"
    find "$suite_dir" -path "*/source/Sources" -type f -exec cat {} \; > "$sources_file"
    if [ ! -s "$sources_file" ]; then
        echo "Warning: No Sources files found for suite '$suite' under $suite_dir"
        touch "$sources_file"
    fi
}

if [ -n "$METADATA" ]; then
    if [ ! -d "$METADATA" ]; then
        echo "Error: Metadata folder '$METADATA' does not exist"
        exit 1
    fi

    # $2 = newer prefix, $3 = older prefix
    distrotracker --local-dir "$METADATA" --dist "$2" "$3"

    for suite in "$2" "$3"; do
        generate_metadata_for_suite "$suite" || exit 1
    done
fi

countgrepunsat() {
    grep -P -A 5 "^\s{5}pkg1?:" | grep -P "^\s{6}(unsat-|package:)" | paste - - | sort | uniq -c | sort -nr
}

showhead() {
    local n="${1:-10}"
    awk -v n="$n" '
        NR <= n {print}
        END {print "Displaying first " n " of " NR " total lines"}
    '
}

if [ "$OPT_ONESHOT" = true ]; then
    echo ""
    echo "Baseline dose-debcheck:"
    dose-debcheck "${EXTRA_PARAMS[@]}" --latest 1 \
        --deb-native-arch=amd64 -e -f $3_Packages | countgrepunsat | showhead || true
    echo ""
    echo "Baseline dose-builddebcheck:"
    dose-builddebcheck "${EXTRA_PARAMS[@]}" --latest 1 \
        --deb-native-arch=amd64 -e -f $3_Packages $3_Sources | countgrepunsat | showhead || true
    echo ""
fi


base_name="$1"
counter=0

filename=$(printf "%s.%03d" "$base_name" $counter)

cat > "$filename.bin"
cat $filename.bin \
    | python3 $SD/predose.py --log-file $base_name.log --resolve-src -c $2_Packages > $filename.src

echo "" | python3 $SD/predose.py --log-file $base_name.log -c $2_Packages $3_Packages > ${base_name}_Packages
echo "" | python3 $SD/predose.py --log-file $base_name.log -c $2_Sources $3_Sources > ${base_name}_Sources

grep-dctrl -s Package -n '' $2_Packages > ${base_name}.origin.list

cat -n > ${base_name}.builddebcheck.log.tmp

echo ""

while true; do

    ((counter++)) || true
    next_filename=$(printf "%s.%03d" "$base_name" $counter)

    # resolve to src on orig and target
    cat $filename.bin \
        | python3 $SD/predose.py --log-file $base_name.log --resolve-src -c $2_Packages >> $filename.src
    cat $filename.bin \
        | python3 $SD/predose.py --log-file $base_name.log --resolve-src -c $3_Packages >> $filename.src

    if [ "$OPT_BINONLY" = false ]; then
    # resolve src to bins on target, remove from target bin
    cat $filename.src \
        | python3 $SD/predose.py --log-file $base_name.log --resolve-bin -c ${base_name}_Packages \
        | python3 $SD/predose.py --log-file $base_name.log --remove -c ${base_name}_Packages > ${base_name}_Packages.tmp && \
        mv -f ${base_name}_Packages.tmp ${base_name}_Packages
    fi
    # remove without resolve
    cat $filename.bin \
        | python3 $SD/predose.py --log-file $base_name.log --remove -c ${base_name}_Packages > ${base_name}_Packages.tmp && \
        mv -f ${base_name}_Packages.tmp ${base_name}_Packages

    if [ "$OPT_BINONLY" = false ]; then

    # resolve to src on orig, remove from target src
    cat $filename.src \
        | python3 $SD/predose.py --log-file $base_name.log --remove -c ${base_name}_Sources > ${base_name}_Sources.tmp && \
        mv -f ${base_name}_Sources.tmp ${base_name}_Sources
    fi

    if [ "$OPT_REMOVEONLY" = false ]; then # skip all implantations if true

    # bin implantation
    cat $filename.bin \
        | python3 $SD/predose.py --log-file $base_name.log -c $2_Packages ${base_name}_Packages > ${base_name}_Packages.tmp && \
        mv -f ${base_name}_Packages.tmp ${base_name}_Packages

    # all-bin implantation
    if [ "$OPT_ONLYUNSAT" = false ]; then
    cat $filename.src \
        | python3 $SD/predose.py --log-file $base_name.log --resolve-bin -c $2_Packages \
        | python3 $SD/predose.py --log-file $base_name.log -c $2_Packages ${base_name}_Packages > ${base_name}_Packages.tmp && \
        mv -f ${base_name}_Packages.tmp ${base_name}_Packages
    fi

    if [ "$OPT_BINONLY" = false ]; then
    # src implantation
    cat $filename.src \
        | python3 $SD/predose.py --log-file $base_name.log -c $2_Sources ${base_name}_Sources > ${base_name}_Sources.tmp && \
        mv -f ${base_name}_Sources.tmp ${base_name}_Sources
    fi

    fi # removeonly

    echo -n > $next_filename.bin
    echo -n > $next_filename.src

    grepunsat() {
        grep -P -A 5 "^\s{5}pkg1?:" | grep -P "^\s{6}(unsat-|package:)" | paste - - | sort -u
    }

    awkunsat() {
        awk -v OPT="$OPT_REMOVEONLY" '{
            pkg = $2
            dep = $4
            sub(/:.*/, "", dep)
            if (OPT == "true")
                if ($0 ~ /unsat-conflict:/) {
                    dep_part = $0
                    sub(/.*unsat-conflict: /, "", dep_part)
                    n = split(dep_part, deps, " \\| ")
                    for (i = 1; i <= n; i++) {
                        gsub(/:.*/, "", deps[i])
                        print deps[i]
                    }
                }
                else {
                    print pkg
                }
            else {
                if ($0 ~ /unsat-dependency:.*\([<=]/) {
                    print pkg
                }
                dep_part = $0
                sub(/.*unsat-dependency: /, "", dep_part)
                n = split(dep_part, deps, " \\| ")
                for (i = 1; i <= n; i++) {
                    gsub(/:.*/, "", deps[i])
                    print deps[i]
                }
            }
        }'
    }

    # check binary packages in dependencies, broken due to low dependent versions
    if [ "$OPT_CHECKONLY" = true ]; then
        EXTRA_PARAMS=(--checkonly "$(paste -sd, <(cat ${base_name}.*.bin | sort -u | grep -v "^\s*$" | sed 's/$/:amd64/'))")
    fi
    dose-debcheck "${EXTRA_PARAMS[@]}" --latest 1 --deb-native-arch=amd64 -e -f ${base_name}_Packages \
        > ${base_name}.debcheck.log.tmp || true &

    pid=$!

    # check src and append to bin, broken due to low dependent versions
    if [ "$OPT_CHECKONLY" = true ]; then
        EXTRA_PARAMS=(--checkonly "$(paste -sd, <(cat ${base_name}.*.src | sort -u | grep -v "^\s*$"))")
    fi
    if [ "$OPT_BINONLY" = false ]; then
    dose-builddebcheck "${EXTRA_PARAMS[@]}" --latest 1 --deb-native-arch=amd64 -e -f ${base_name}_Packages ${base_name}_Sources \
        > ${base_name}.builddebcheck.log.tmp || true
    fi

    wait $pid || true

    cat ${base_name}.debcheck.log.tmp | grepunsat | awkunsat | sort -u >> $next_filename.bin || true
    if [ "$OPT_NOSRCFIX" = false ]; then
    cat ${base_name}.builddebcheck.log.tmp | grepunsat | awkunsat | sort -u >> $next_filename.bin || true
    fi

    # select packages dependent on deps missing from the origin
    dependentonmissing() {
        local pkg_list_file="$1"
        awk -v pkg_list_file="$pkg_list_file" \
        '
        function isinmetadata(dep) {
            cmd = "grep ^" dep "$ " pkg_list_file
            return (system(cmd) == 0)
        }
        {
            pkg = $2
            dep = $4
            sub(/:.*/, "", dep)
            if (!isinmetadata(dep)) {
                print pkg
            }
        }'
    }

    if [ "$OPT_REMOVEONLY" = false ]; then
    cat ${base_name}.debcheck.log.tmp | grepunsat | dependentonmissing ${base_name}.origin.list >> $next_filename.bin || true
    if [ "$OPT_NOSRCFIX" = false ]; then
    cat ${base_name}.builddebcheck.log.tmp | grepunsat | dependentonmissing ${base_name}.origin.list >> $next_filename.src || true
    fi
    fi

    # print
    echo -n "$(date '+%Y-%m-%d %H:%M:%S') "
    echo -n "$filename: "
    grep -P '^[a-z]+\-packages:' ${base_name}.debcheck.log.tmp | sed "s/-packages//" | paste -sd '\t' | tr -d '\n' || true
    echo -n " "
    grep -P '^[a-z]+\-packages:' ${base_name}.builddebcheck.log.tmp | sed "s/-packages//" | paste -sd '\t' || true

    cat ${base_name}.debcheck.log.tmp >> ${base_name}.debcheck.log
    cat ${base_name}.builddebcheck.log.tmp >> ${base_name}.builddebcheck.log

    sort -u -o "$filename.bin" "$filename.bin"
    sort -u -o "$next_filename.bin" "$next_filename.bin"
    sort -u -o "$filename.src" "$filename.src"
    sort -u -o "$next_filename.src" "$next_filename.src"

    cp -f ${base_name}_Sources ${base_name}_Sources.prev
    cp -f ${base_name}_Packages ${base_name}_Packages.prev

    if [ "$OPT_ONESHOT" = true ]; then
        echo ""
        echo "Regression dose-debcheck:"
        cat ${base_name}.debcheck.log.tmp | countgrepunsat | showhead || true
        echo ""
        echo "Regression dose-builddebcheck:"
        cat ${base_name}.builddebcheck.log.tmp | countgrepunsat | showhead || true
        echo ""
        echo "Only one iteration requested, exit"
        exit 0
    fi

    if cmp -s "$filename.bin" "$next_filename.bin" && cmp -s "$filename.src" "$next_filename.src"; then
        echo "Stopping: '$next_filename' has identical content to '$filename'"
        exit 0
    fi

    if [ $counter -ge 999 ]; then
        echo "Iteration limit reached"
        exit 1
    fi

    filename="$next_filename"
done
